name: main_workflow
on: [push]
jobs:
  Linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_codigo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Send discord message
        uses: ./.github/actions/discord/
        with:
          discord_token: ${{ secrets.BOT_TOKEN }}
          id_channel: ${{ secrets.CHANNEL_ID }}
